### ISSUE TITLE
Git Migration Plan

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#163]
# GITHUB MIGRATION PLAN
## Task Items
- Task items for this effort will be tracked here: https://github.com/twisted-infra/braid/milestones/Migrate-to-Git
## Objectives
-  https://github.com/twisted/twisted will be the "repository of truth" for Twisted.
- Twisted releases will be done from GitHub #156
- the Twisted developers who are now "core committers" for SVN, will be given access to be "core committers" to https://github.com/twisted/twisted . Committers to Twisted must have 2FA enabled, existing Twisted org members will get given access during the migration, but those that are not part of the Twisted org can be emailed with a mention that 2FA is required, and we can invite once that is set up. #158 #164
- Trac will still be used for filing tickets.  Filing issues in GitHub will be disabled. #165
### Staging Trac
- [x] Create staging DNS entry #185
- [x] Create a staging Trac server #167
- [x] In 'staging' Trac, install https://github.com/trac-hacks/trac-GitHub #168
- [x] In 'staging' GitHub repo add the webhook to poke the 'staging' Trac #169
- [x] Make sure that existing Trac changeset links go to the SVN repo viewer, and new Git changesets redirect from Trac to GitHub. #138
- [x] Have a git mirror managed by Trac but set up using braid #139 
- [x] Make sure that we have recent dependencies in virtualenvs #1
### Repo access and Git history
- [x] Copy `twisted/twisted` to `twisted/twisted-staging` and push this 'staging' repo to GitHub, NOT under `twisted/twisted` but under `twisted/twisted-staging` #172
- [x] Make the base branch "master" instead of trunk #166 
- [x] Make sure that all users who have SVN commit access have a GitHub account which can commit to the Twisted repository on GitHub, #158 #164
- [x] Investigate `.mailmap` and similar to alter/amend history to update existing contributor metadata to be their current GitHub email #170
- [x] Investigate to see if we can trim out older branches on the existing git mirror, and only leaving tags and trunk/master. #171
- [x] Configure the master branch as a protected branch #146
### IRC
- [x] Change Kenaan IRC bot to monitor GitHub #137 #142
- [x] Commit some things to the staging GitHub repo, make sure the staging trac picks them up, and it's propagated to Kenaan and such.
### Highscores
- [x] Just queries the Trac db so should be fine
### Commit mailing list
- [x] Migrate commit mailer to Git hook #92 
### Codespeed
- Do we need to care about this service?
### Buildbot
- [ ] Migrate to Nine (see #178)
### Documentation
- [x] Update all wiki documentation to change all references to getting code from Subversion, to getting code from GitHub. https://github.com/twisted-infra/braid/issues/159
- [x] Update Release Engineering documentation for doing a release from GitHub, https://github.com/twisted-infra/braid/issues/156
- [ ] Update links to new hosting URL #148 
### Migration schedule
- [x] Pick a weekend where Amber isn't doing anything, send out warnings, queue up a ticket for testing #176
- [x] Send e-mail one week before scheduled maintenance. #175
- [x] Before the maintenance begins, send another HEADSUP e-mail. #176
- [x] Disable commits to Subversion: http://stackoverflow.com/questions/2411122/how-to-freeze-entire-svn-repository-to-make-it-read-only #174
- [x] Install trac-GitHub as on the staging on the production trac, and set up `twisted/twisted` to connect to the production webhook. #173
- [x] Merge the ticket queued up for testing, make sure production Trac knows about it.
- [x] Send HEADSUP e-mail saying that GitHub migration is done, #68
- [x] Delete the `twisted/twisted-staging` repo.  but maybe keep it for future work/testing #172

**Comment by adiroiban** [comment]
All tickets from the milestone are references in this ticket

**Comment by adiroiban** [comment]
Why is buildbot migration to v0.9 part of the git migration plan?

**Comment by rodrigc** [comment]
This ticket seems outdated, now that Twisted uses GitHub to host its source code.
