### ISSUE TITLE
☂ Migrate to BuildBot Nine

### ISSUE THREAD

**Issue by hawkowl** [twisted-infra/braid#178]
BuildBot Nine has GitHub integration, and our current BuildBot is a mess that sorely needs upgrading.

Things that need doing:
# Migrating Buildsteps
- [x] Migrate the Trial steps
- [ ] Migrate the PyFlakes steps
- [ ] Migrate the Sphinx builder steps
# Nine Upgrades
- [x] New "twisted view", like the old boxes view
- [ ] Configure IRC (maybe?)
- [ ] Configure authz
- [x] Migrate SVN commit hooks to GitHub, https://github.com/twisted-infra/braid/issues/141, https://github.com/twisted-infra/braid/issues/147
- [x] Update all builders to get code from GitHub, https://github.com/twisted-infra/braid/issues/73, https://github.com/twisted-infra/braid/issues/141
- [x] Remove SVN related branch name handling #73

**Comment by glyph** [comment]
I am not clear what checking off the items in the list means if the ticket is still open. Before we close this, can we get separate tickets for each of the items in the todo list?

**Comment by rodrigc** [comment]
@adiroiban you have spent time lately with buildbot 0.8.  I'm just curious, are you familiar with buildbot 0.9?  What are the issues with upgrading to it?

**Comment by adiroiban** [comment]
What do we get by upgrading to 0.9? 
What is wrong with 0.8 ? :)
I have not used 0.9.

I think that I went for 0.8 as this works and required the less amount of effort.
As you can see from this ticket, in Twisted there are a couple of extensions to buildbot and migrating them takes time.

For me buildbot 0.8 works and I prefer to spend time on other activities :)

We are still using a forked buildbot version.

https://github.com/twisted-infra/braid/blob/51e495096c39f30399246e92aaa32812d5b7c327/services/buildbot/fabfile.py#L99

**Comment by rodrigc** [comment]
I have become an active contributor to buildbot so have some insights:
* buildbot 8 has no maintainer, and is not actively maintained upstream
* buildbot 9 is under active development, has better support for Docker, and container providers like hyper.sh
* buildbot 9 works on python 3, buildbot 8 does not and never will

For the purposes of the Twisted migration to GitHub, I think buildbot 9 is a non-issue,
because Twisted managed to migrate to GitHub with buildbot 8, and it works.

Long term, it would be nice if Twisted used upstream buildbot, rather than a forked old version of buildbot.

buildbot guys are really great to work with, and they heavily use Twisted features.  They are a fantastic source of bug reports against Twisted itself, since they are such heavy users.

**Comment by adiroiban** [comment]
It would be nice to have a newer buildbot.

For now I am working to get the existing one up and running in Vagrant.

I think that some of the suggested tasks  can be done in the current buildbot, no need to wait for upgrade.

From me, the main issue with Twisted's buildbot deployment is that it tries to be smart so it has a lot of customization.

We no longer need PyFlakes or sphinx builder steps.
Pyflakes can be a simple plain shell and fail on any error.
In the past Twisted's buildbot was trying to be smart and do the diff on errors and only fail on new errors.

So before looking at migrating to latest buildbot, maybe we can look at simplifying the current buildbot instalaltion. And this should make any upgrade much easier

**Comment by rodrigc** [comment]
Sounds good to me.

**Comment by adiroiban** [comment]
The main task should be https://github.com/twisted-infra/braid/issues/222 

PS. i don't know why we are using umbrella tickets and not milestones :)

**Comment by glyph** [comment]
Hello from 2 years later :). 

How's this doing?

**Comment by rodrigc** [comment]
I think this ticket is no longer relevant, since Twisted now uses a mixture of GitHub Actions, Azure CI, CircleCI, and TravisCI, instead of Buildbot.
